### ISSUE TITLE
Buildcom errors out and says it's aborting due to existing component even if it's not true

### ISSUE THREAD

**Issue by foxleigh81** [foxleigh81/buildcom#11]
**Describe the bug**
When I create a component I get the following error: 

```
Error: packages/components/my-test already exists, aborting
    at throwError (/Users/foxleigh81/dev/buildcom/scripts/throw-error.js:2:11)
    at generateDirectory (/Users/foxleigh81/dev/buildcom/scripts/generate-directory.js:16:9)
    at dirArray.length.dirArray.map.dirName (/Users/foxleigh81/dev/buildcom/scripts/component-generator.js:64:33)
    at Array.map (<anonymous>)
    at comGen (/Users/foxleigh81/dev/buildcom/scripts/component-generator.js:64:18)
    at Object.<anonymous> (/Users/foxleigh81/dev/buildcom/index.js:27:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

The error does not seem to cause the component generation to fail though, everything gets generated without issue.

**To Reproduce**
It happens every time I use the app with the `buildcom` command

**Expected behavior**
Component produced without errors

**Desktop (please complete the following information):**
http://mybrowser.fyi/report/5e457a665a9f1a0015900832

**Comment by foxleigh81** [comment]
v0.2.6 no longer has this bug as I've temporarily removed the existing component detector functionality. I'm leaving the bug report open though as the feature needs to be reinstated without the error.
